Repository maingockien01/comp4350-team8, pull requests merged in 2024-03, with the labels that each got.

#62 Issue 46: fix e2e test job in CI
  .github/workflows/ci.yml
  docker/nodejs/Dockerfile
Labels: DevOps

#68 Issue#67 fix blank page
  .prettierrc
  apps/backend/test/e2e/hello.e2e.ts
  apps/backend/test/unit/auth/auth.controller.unit.ts
  apps/backend/test/unit/auth/auth.service.unit.ts
  apps/frontend/src/App.tsx
  src/database/database.module.ts
Labels: bug

#73 Issue#69 update database 2
  apps/backend/src/entities/course.entity.ts
  apps/backend/src/entities/degree.entity.ts
  apps/backend/src/entities/section.entity.ts
  apps/backend/src/entities/term.entity.ts
  apps/backend/src/entities/user.entity.ts
Labels: enhancement

#75 Update
  apps/SQL queries/course_prerequisites_course.sql
  apps/SQL queries/courses_prerequisite_relation.sql
  apps/SQL queries/recommended_courses_relation.sql
  apps/SQL queries/section.sql
  apps/SQL queries/sections_contain_users_relation.sql
  apps/SQL queries/term.sql
  apps/SQL queries/terms_contain_courses_relation.sql
Labels: enhancement

#77 Update structure/logic
  apps/SQL queries/course.sql
  apps/SQL queries/section.sql
  apps/SQL queries/sections_contain_users_relation.sql
  apps/backend/src/app.module.ts
  apps/backend/src/courses/course.controller.ts
  apps/backend/src/courses/course.module.ts
  apps/backend/src/courses/course.service.ts
  apps/backend/src/entities/course.entity.ts
  apps/backend/src/routes.module.ts
  apps/backend/src/terms/term.service.ts
  apps/backend/test/unit/degrees/degree.controller.unit.ts
  apps/backend/test/unit/term/term.controller.unit.ts
  apps/frontend/src/App.tsx
  apps/frontend/src/Components/Navbar.tsx
  apps/frontend/src/Screens/Calendar.tsx
  apps/frontend/src/Screens/MainScreen.tsx
  apps/frontend/src/Utils/CookieFunctions.ts
  apps/frontend/src/Utils/getCurrentUserID.ts
  packages/types/dtos/course/course.dto.ts
Labels: enhancement

#80 Update Calendar page to use JWT
  apps/frontend/src/Components/Navbar.tsx
  apps/frontend/src/Screens/Calendar.tsx
Labels: bug

#81 Issue#70: Prevent user from going to Login/Signup pages when logged in
  apps/backend/src/users/user.course.controller.ts
  apps/frontend/src/App.tsx
  apps/frontend/src/Components/Navbar.tsx
Labels: bug

#85 User Profile Page
  apps/SQL queries/users.sql
  apps/backend/src/auth/auth.module.ts
  apps/backend/src/entities/user.entity.ts
  apps/backend/src/profile/profile.controller.ts
  apps/backend/src/profile/profile.service.ts
  apps/backend/src/users/user.course.controller.ts
  apps/backend/src/users/users.service.ts
  apps/frontend/package.json
  apps/frontend/src/App.tsx
  apps/frontend/src/Components/Navbar.tsx
  apps/frontend/src/Components/UserProfileForm.tsx
  apps/frontend/src/Screens/UserProfileScreen.tsx
  apps/frontend/src/css/UserProfileForm.css
  apps/frontend/src/css/UserProfileScreen.css
  packages/types/dtos/profile/update.dto.ts
  packages/types/dtos/user/user.dto.ts
  yarn.lock
Labels: Account Management

#88 Issue#74: Fix user.controller unit test
  apps/backend/test/unit/user/user.controller.unit.ts
Labels: bug, DevOps

#91 Fix bug front end import entity
  apps/SQL queries/degree.sql
  apps/SQL queries/section.sql
  apps/SQL queries/terms_contain_courses_relation.sql
  apps/backend/src/courses/course.controller.ts
  apps/backend/src/courses/course.module.ts
  apps/backend/src/courses/course.service.ts
  apps/backend/src/entities/section.entity.ts
  apps/backend/src/entities/user.entity.ts
  apps/backend/src/routes.module.ts
  apps/backend/src/sections/section.controller.ts
  apps/backend/src/sections/section.module.ts
  apps/backend/src/sections/section.service.ts
  apps/backend/src/terms/term.controller.ts
  apps/backend/src/terms/term.service.ts
  apps/backend/src/users/user.course.controller.ts
  apps/backend/src/users/user.course.module.ts
  apps/backend/src/users/user.course.service.ts
  apps/backend/test/unit/term/term.controller.unit.ts
  apps/frontend/src/App.tsx
  apps/frontend/src/Screens/AddDropCourses.tsx
  apps/frontend/src/Screens/Calendar/Calendar.tsx
  apps/frontend/src/Screens/CoursesScreen.tsx
  apps/frontend/src/Screens/DetailScreen.tsx
  apps/frontend/src/Screens/LookUpScreen.tsx
  packages/types/dtos/location/location.dto.ts
  packages/types/dtos/section/section.dto.ts
  packages/types/dtos/term/term.dto.ts
  tsconfig.json
Labels: bug

#95 Add comments to code + fix logged in bug
  apps/SQL queries/section.sql
  apps/backend/src/auth/auth.service.ts
  apps/backend/test/e2e/_helpers/User.ts
  apps/backend/test/e2e/userCourse/userCourse.controller.e2e.ts
  apps/backend/test/e2e/userCourse/userCourse.service.e2e.ts
  apps/frontend/src/Screens/AddDropCourses.tsx
  apps/frontend/src/Screens/CoursesScreen.tsx
  apps/frontend/src/Screens/DetailScreen.tsx
  apps/frontend/src/Screens/MainScreen.tsx
Labels: bug

#96 Unit tests for account management
  apps/backend/src/auth/auth.service.ts
  apps/backend/src/users/user.course.controller.ts
  apps/backend/test/unit/auth/auth.controller.unit.ts
  apps/backend/test/unit/auth/auth.service.unit.ts
  apps/backend/test/unit/user/user.controller.unit.ts
  apps/frontend/src/App.tsx
  apps/frontend/src/Components/Navbar.tsx
  apps/frontend/src/Screens/Calendar/Calendar.tsx
  apps/frontend/src/Screens/MainScreen.tsx
  apps/frontend/src/Utils/CookieFunctions.ts
Labels: Account Management

#99 Apply fixes
  apps/backend/test/unit/user/user.controller.unit.ts
Labels: bug, DevOps

#104 fix invalid section id
  apps/SQL queries/section.sql
  apps/backend/src/users/user.course.service.ts
  apps/backend/test/unit/courses/course.service.unit.ts
  apps/backend/test/unit/degrees/degree.controller.unit.ts
  apps/backend/test/unit/degrees/degree.service.unit.ts
  apps/backend/test/unit/section/section.controller.unit.ts
  apps/backend/test/unit/term/term.controller.unit.ts
  apps/backend/test/unit/user/user.controller.unit.ts
Labels: bug

#107 Frontend error handling
  apps/SQL queries/degree.sql
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/auth.service.ts
  apps/backend/test/unit/auth/auth.controller.unit.ts
  apps/backend/test/unit/auth/auth.service.unit.ts
  apps/frontend/src/Components/LoginForm.tsx
  apps/frontend/src/Components/Navbar.tsx
  apps/frontend/src/Components/SignupForm.tsx
  apps/frontend/src/Components/UserProfileForm.tsx
  apps/frontend/src/Screens/LoginScreen.tsx
  apps/frontend/src/Screens/SignupScreen.tsx
  apps/frontend/src/Utils/CookieFunctions.ts
Labels: enhancement, Account Management

#109 Unit tests & Frontend fixes
  apps/backend/test/unit/auth/auth.controller.unit.ts
  apps/backend/test/unit/profile/profile.controller.unit.ts
  apps/frontend/src/Screens/DetailScreen.tsx
  apps/frontend/src/Screens/Roadmap/Roadmap.tsx
  apps/frontend/src/css/RoadmapScreen.css
Labels: enhancement
