Repository maingockien01/comp4350-team8, pull requests merged in 2024-02, with the labels that each got.

#43 Set cookie for user
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/auth.service.ts
Labels: Account Management

#44 Login/signup frontend
  apps/frontend/index.html
  apps/frontend/package.json
  apps/frontend/src/App.tsx
  apps/frontend/src/Components/Assets/background.jpg
  apps/frontend/src/Components/Assets/background.jpgZone.Identifier
  apps/frontend/src/Components/LoginForm.tsx
  apps/frontend/src/Screens/AddDropCourses.tsx
  apps/frontend/src/Screens/LoginScreen.tsx
  apps/frontend/src/Screens/MainScreen.tsx
  apps/frontend/src/css/LoginForm.css
  apps/frontend/src/css/LoginScreen.css
  apps/frontend/src/index.css
  apps/frontend/src/index.tsx
  yarn.lock
Labels: Account Management

#45 Degree roadmap
  apps/SQL queries/course_prerequisites_course.sql
  apps/SQL queries/degree.sql
  apps/SQL queries/degree_recommended_courses_course.sql
  apps/backend/src/courses/course.service.ts
  apps/backend/src/degrees/degree.controller.ts
  apps/backend/src/degrees/degree.service.ts
  apps/backend/src/entities/course.entity.ts
  apps/backend/src/entities/degree.entity.ts
  apps/backend/test/unit/courses/course.service.unit.ts
  apps/backend/test/unit/degree/degree.controller.unit.ts
  apps/backend/test/unit/degrees/degree.controller.unit.ts
  apps/backend/test/unit/degrees/degree.service.unit.ts
  apps/backend/test/unit/term/term.controller.unit.ts
  apps/frontend/src/App.tsx
  apps/frontend/src/Components/CourseTree/CourseTree.tsx
  apps/frontend/src/Screens/Roadmap.tsx
  apps/frontend/src/Screens/Roadmap/Roadmap.tsx
  apps/frontend/src/Screens/Roadmap/data.ts
  packages/types/domain/roadmap.model.ts
  packages/types/dtos/course/course.dto.ts
  packages/types/dtos/degree/degree.dto.ts
Labels: Roadmap

#57 Testing Plan
  docs/testing_plan/Team8 - Testing Plan.pdf
  docs/testing_plan/Team8 - Testing Plan.pdfZone.Identifier
  docs/testing_plan/testing_plan_v1.pdf
Labels: documentation
